### PR TITLE
add new task ODD and Even Number

### PR DESCRIPTION
**Pull request by dlincolnstory**

### CODE REVIEW

**Review by nikaknowles — APPROVED** [review]

**Comment by Balqees77** [comment]
I got it thank you!

**Review by Balqees77 — COMMENTED** [review]
good to go

**Review by Balqees77 — COMMENTED** [review]
good to go

**Review by Balqees77 — COMMENTED** [review]
good to go!

**Review by Balqees77 — COMMENTED** [review]
good

**Review by Balqees77 — COMMENTED** [review]
good to go

**Pull request merged**
